# Generated by Django 5.0.2 on 2024-03-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_Post',
            field=models.ImageField(default=123, upload_to=None),
            preserve_default=False,
        ),
    ]
